version: '3'
services:
    client:
        image: 'ausgeflippte/docker-multi-client'
        mem_limit: 128m
        hostname: client
    api:
        image: 'ausgeflippte/docker-multi-api'
        mem_limit: 128m
        hostname: api
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - PGUSER=$PGUSER
            - PGHOST=$PGHOST
            - PGDATABASE=$PGDATABASE
            - PGPASSWORD=$PGPASSWORD
            - PGPORT=$PGPORT
    worker:
        image: 'ausgeflippte/docker-multi-worker'
        mem_limit: 128m
        hostname: worker
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
    nginx:
        image: 'ausgeflippte/docker-multi-nginx'
        mem_limit: 128m
        hostname: nginx
        ports:
            - '3050:80'
